### ISSUE TITLE
let winTile = 2048 != winning when you get a 2048 tile

### ISSUE THREAD

**Issue by JorrieB** [MakeSchool/2048-SpriteBuilder-Swift#3]
The player should win when a single 2048 tile appears. Because we increase the actual value of the tile in a CCActionSequence but we check if there exists a tile of the value 2048 before that sequence is complete, we are actually checking the old values of the tile. There are two solutions:

1) Simply change the 'winTile' variable to 1024 and explain it away in the tutorial
2) Check the win condition after the move is complete.

Tell me which you would prefer and I'll adapt tutorial as necessary.

**Comment by dionlarson** [comment]
Check after
